90 genomics
utsw-bicf/pandiseased pull request #104
Opened 2020-01-14 22:26 UTC by mingjiecn

Add biospecimen and biolibrary.

2020-01-14 22:28 UTC, mingjiecn commented
accession is not working as key.

2020-01-21 19:33 UTC, vsmalladi commented on src/encoded/schemas/bioreplicate.json
> +        "rbns_protein_concentration": {
Delete rbns properties

2020-01-21 19:38 UTC, vsmalladi requested changes
Add Biolibrary.md, Bioreplicate.md annd Biofile.md files for change logs

2020-02-03 16:40 UTC, vsmalladi approved these changes

2020-02-03 16:47 UTC, merged