12 mets
utsw-bicf/pandiseased pull request #232
Opened 2020-07-22 21:25 UTC by mingjiecn

Close #12 
Close #61 
![image](https://user-images.githubusercontent.com/44071821/88230327-d52d3a00-cc37-11ea-9b63-5cc220850139.png)

![image](https://user-images.githubusercontent.com/44071821/88230371-e8d8a080-cc37-11ea-9ec4-23cc4f3f25fc.png)

2020-07-26 03:58 UTC, vsmalladi requested changes

2020-07-26 03:58 UTC, vsmalladi commented on src/encoded/types/patient.py
> +                if radiation_object['site_general'] != "Kidne, right" and radiation_object['site_general'] != "Kidney, thrombus" and radiation_object['site_general'] != "Kidney, left" and radiation_o
Should be "Kidney" instead of "Kidne"

2020-07-27 15:07 UTC, mingjiecn commented on src/encoded/types/patient.py
> +                if radiation_object['site_general'] != "Kidne, right" and radiation_object['site_general'] != "Kidney, thrombus" and radiation_object['site_general'] != "Kidney, left" and radiation_o
Fixed.

2020-07-27 17:02 UTC, vsmalladi approved these changes
Looks great.

2020-07-27 17:03 UTC, merged