257 search
utsw-bicf/pandiseased pull request #268
Opened 2020-10-16 19:17 UTC by mingjiecn

close #267 

close #266 
![image](https://user-images.githubusercontent.com/44071821/96297660-cf38c200-0fb6-11eb-9050-6954d7e2e040.png)

close #263 after real data is updated:
![image](https://user-images.githubusercontent.com/44071821/96297753-fabbac80-0fb6-11eb-8ff4-de39197c4a3e.png)

close #261 after real data is updated:
![image](https://user-images.githubusercontent.com/44071821/96299738-18d6dc00-0fba-11eb-983e-363144e4f0e2.png)

close #259 
![image](https://user-images.githubusercontent.com/44071821/96298360-f47a0000-0fb7-11eb-9ef9-342061742550.png)

close #258 after real data is updated:
![image](https://user-images.githubusercontent.com/44071821/96299573-e5944d00-0fb9-11eb-85ed-842bcaa7be80.png)

close #257 
![image](https://user-images.githubusercontent.com/44071821/96299796-3441e700-0fba-11eb-9c45-bc659671be45.png)

2020-10-19 19:01 UTC, vsmalladi commented
Updated real data to change Total -> Radical: close #258

2020-10-19 19:29 UTC, vsmalladi commented
Updated real data close #261

2020-10-19 22:38 UTC, vsmalladi commented
Updated real data close #263

2020-10-20 13:23 UTC, vsmalladi requested changes
Minor typos but everything looks good.

2020-10-20 13:23 UTC, vsmalladi commented on src/encoded/schemas/biospecimen.json
> +            "title": "pN Stage at Presentaion"
@mingjiecn Spelling error should be "Presentation"

2020-10-20 13:23 UTC, vsmalladi commented on src/encoded/schemas/biospecimen.json
> +            "title": "pM Stage at Presentaion"
@mingjiecn Spelling error should be "Presentation"

2020-10-20 13:23 UTC, vsmalladi commented on src/encoded/schemas/biospecimen.json
> +            "title": "TNM Stage at Presentaion"
@mingjiecn Spelling error should be "Presentation"

2020-10-20 13:23 UTC, vsmalladi commented on src/encoded/schemas/patient.json
> +            "title": "pT Stage at Presentaion"
@mingjiecn Spelling error should be "Presentation"

2020-10-20 13:23 UTC, vsmalladi commented on src/encoded/schemas/patient.json
> +            "title": "pN Stage at Presentaion"
@mingjiecn Spelling error should be "Presentation"

2020-10-20 13:23 UTC, vsmalladi commented on src/encoded/schemas/patient.json
> +            "title": "pM Stage at Presentaion"
@mingjiecn Spelling error should be "Presentation"

2020-10-20 13:23 UTC, vsmalladi commented on src/encoded/schemas/surgery.json
> +            "title": "pT Stage at Presentaion"
@mingjiecn Spelling error should be "Presentation"

2020-10-20 13:23 UTC, vsmalladi commented on src/encoded/schemas/surgery.json
> +            "title": "pN Stage at Presentaion"
@mingjiecn Spelling error should be "Presentation"

2020-10-20 13:23 UTC, vsmalladi commented on src/encoded/schemas/surgery.json
> +            "title": "pM Stage at Presentaion"
@mingjiecn Spelling error should be "Presentation"

2020-10-20 13:23 UTC, vsmalladi commented on src/encoded/schemas/surgery.json
> +            "title": "TNM Stage at Presentaion"
@mingjiecn Spelling error should be "Presentation"

2020-10-20 13:50 UTC, mingjiecn commented
corrected the typo

2020-10-20 15:59 UTC, vsmalladi approved these changes

2020-10-20 16:26 UTC, merged