302 dict
utsw-bicf/pandiseased pull request #314
Opened 2020-12-15 21:43 UTC by mingjiecn

close #302 
![image](https://user-images.githubusercontent.com/44071821/102276264-2c37f200-3eec-11eb-927c-05522d7720ad.png)

2020-12-15 23:04 UTC, vsmalladi requested changes

2020-12-15 23:04 UTC, vsmalladi commented on src/encoded/tests/data/inserts/page.json
> +            "body": "<p>:</p>\n\n<h2>Terminology and Definitions</h2>\n\n<h3>Patient Demographics</h3>\n\n<p><strong>Patient ID (KCEPTXXXXXX)</strong>: A unique (11-digit) identifier for each patient
@mingjiecn Fix spelling for "availabl"

2020-12-15 23:22 UTC, mingjiecn commented on src/encoded/tests/data/inserts/page.json
> +            "body": "<p>:</p>\n\n<h2>Terminology and Definitions</h2>\n\n<h3>Patient Demographics</h3>\n\n<p><strong>Patient ID (KCEPTXXXXXX)</strong>: A unique (11-digit) identifier for each patient
done

2020-12-16 01:41 UTC, vsmalladi approved these changes

2020-12-16 01:41 UTC, merged