367 prbug
utsw-bicf/pandiseased pull request #368
Opened 2021-01-08 16:25 UTC by SenseCode

close issue #367

![image](https://user-images.githubusercontent.com/38848214/104039101-8cdce680-519b-11eb-8670-36baf97000cb.png)
![image](https://user-images.githubusercontent.com/38848214/104039135-9a926c00-519b-11eb-9090-7617a79ff83d.png)

2021-01-09 14:15 UTC, vsmalladi requested changes

2021-01-09 14:15 UTC, vsmalladi commented on src/encoded/static/components/pathologyReportTable.js
> +                                        <dt>Accession</dt>
Can we change this to just say "Pathology Report"

2021-01-11 16:30 UTC, mingjiecn approved these changes

2021-01-11 19:26 UTC, vsmalladi approved these changes

2021-01-11 19:26 UTC, merged