270 clean
utsw-bicf/pandiseased pull request #384
Opened 2021-02-10 14:59 UTC by mingjiecn

close #270

2021-02-18 22:28 UTC, vsmalladi requested changes
File details seemms to be broken. 
<img width="1225" alt="Screen Shot 2021-02-18 at 4 26 55 PM" src="https://user-images.githubusercontent.com/1130240/108429940-3e911d80-7206-11eb-8523-d8604e3e26c0.png">

2021-02-18 23:00 UTC, mingjiecn commented
I can see file detail on my local, not sure what happened.
![image](https://user-images.githubusercontent.com/44071821/108432881-ae090c00-720a-11eb-8520-ca27860fccbc.png)

2021-02-18 23:05 UTC, SenseCode commented
I can pull and test

2021-02-19 16:19 UTC, vsmalladi approved these changes

2021-02-19 16:19 UTC, merged