4 meds
utsw-bicf/pandiseased pull request #77
Opened 2019-11-27 16:41 UTC by SenseCode

Finished medications chart, request to close issue #4

2019-11-27 17:25 UTC, cmonnom requested changes
Good work (see minor changes needed in medicationChart.js and patient.js).
Notes (future improvements):
Let's harmonize gantt charts (same colors, Y-axis labels, etc.) in a separate issue.
Use Collapsable panels (separate issue)

2019-11-27 17:25 UTC, cmonnom commented on src/encoded/static/components/patient.js
> +        console.log(context.medications);
Remove console.log statements

2019-11-27 17:25 UTC, cmonnom commented on src/encoded/static/components/patient.js
> +                            <MedicationChart chartId="medicationChart" data={context.medications} chartTitle="Medications results over time" ></MedicationChart>
Capitalize "over time" to match other titles

2019-11-27 17:25 UTC, cmonnom commented on src/encoded/static/components/medicationChart.js
> +    this.unixToDate();
unixToDate is called in transformDataFun()
Delete this line

2019-11-27 17:28 UTC, cmonnom reviewed
I've also noticed some overflow issues when zooming in sometimes.

2019-11-27 19:00 UTC, SenseCode commented on src/encoded/static/components/patient.js
> +        console.log(context.medications);
Oh, leaky Fish...

2019-12-05 15:09 UTC, cmonnom approved these changes

2019-12-11 19:14 UTC, vsmalladi approved these changes

2019-12-11 19:15 UTC, merged